name: durables

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - econ-ark=0.12.0
  - numpy=1.20
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ruff 
  - nbqa
  - pip
  - pip:
    - EconModel
    - ConSav